[package]
name = "clai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
async-openai = "0.20.0"
bollard = "0.16.1"
tokio = { version = "1.37.0", features = ["full"] }
